### PR TITLE
Re: #32: Changes for the failing Travis-CI tests

### PR DESCRIPTION
**Pull request by CSP197**
Summary of changes:
1. `numerox/data.py`: changed formatting of strings to allow values to be printed
2. `numerox/testing.py`:  fixed alignment of arrays in `micro_data()` function definition
3. `numerox/tests/test_tournament.py`: added `tournament_numbers()` call in lieu of a hard-coded range and updated `test_tournament_all()` function to comply with the Kazutsugi tournament
4. `numerox/tournament.py`: added default `active_only` parameter to `tournament_int2str` and `tournament_str2int` function definitions

Please feel free to ask any questions regarding my changes :)

### CODE REVIEW

**Comment by CSP197** [comment]
This PR is regarding https://github.com/numerai/numerox/issues/32

**Comment by kumikoda** [comment]
hey @CSP197 thanks for the PR! looks like the tests are still broken. Can you take another look at travis? Let me know if you need any help.

**Comment by CSP197** [comment]
Hi @kumikoda,

I've fixed any recurring PEP8 style errors, as well as any errors referencing `nx.logistic` instead of `nx.linear`.

I wanted to ask for some help regarding the `micro_data` function in `numerox\testing.py`, specifically how it's individual indices are created. A lot of the tests use this function, so a kazutsugi column will need to be added here.

A lot of the tests also use a smaller sample dataset (`numerox\tests\tiny_dataset_csv.zip`), similar to the one Numerai releases every week, for its tests. Each tournament is a column on the sample dataset. This file, and `numerox\tests\test_data.hdf` need to be updated to comply with the updated Numerai tournament.

**Comment by kumikoda** [comment]
hey @kwgoodman any quick answers to help @CSP197 out? 

otherwise, let me look into this next week.

**Pull request closed without merging**
